import type { SupabaseClient } from "@supabase/supabase-js"

/**
 * Auto-match Fathom meetings to clients (Phase C.5.b).
 *
 * Pragmatic v1 — title-substring match against client names. Catches the
 * majority of cases ("Suits at Sea en Sebastiaan" → client "Suits at Sea")
 * because Fathom's auto-titles either contain the inviting party's name or
 * the company explicitly. Fancier strategies (email-domain match, fuzzy /
 * alias) come in v2 once we see what slips through.
 *
 * Confidence scale (0..1):
 *  ≥ 0.80 → set link_status='linked' (auto-link)
 *  0.50..0.79 → set link_status='suggested' (visible in Unlinked, awaiting confirmation)
 *  < 0.50 → leave as 'unlinked'
 */

export type ClientForMatch = { mondayItemId: string; name: string }

export type MeetingForMatch = {
  title: string | null
  attendees?: Array<{
    name: string | null
    email: string | null
    email_domain: string | null
    is_external: boolean
  }> | null
}

export type MatchResult = {
  clientId: string
  confidence: number
  strategy: "title_exact" | "title_word" | "attendee_domain"
}

// Words to ignore inside meeting titles when matching. Fathom's autogenerated
// titles smush "Jouw afspraak met X" / "X en Sebastiaan" together — these
// stopwords prevent generic phrasing from polluting the match space.
const STOPWORDS = new Set([
  // Dutch fillers
  "de", "het", "een", "en", "met", "bij", "van", "voor", "tot", "op", "in",
  "jouw", "uw", "je", "afspraak", "gesprek", "kennismaking", "groeisessie",
  "groeicall", "groei", "call", "meeting", "intro", "kickoff", "kick", "off",
  "evaluatie", "review", "update",
  // English fallbacks
  "the", "a", "and", "with", "by", "for",
  // Internal staff names that show up in nearly every title
  "sebastiaan", "sebastian", "roy", "roel", "mike", "anel", "jill", "danny",
  "quintus", "arno",
])

const MIN_CLIENT_NAME_LENGTH = 4

function normalize(s: string): string {
  // NFD-decompose then drop combining marks, so "café" → "cafe" before the
  // ASCII filter strips anything non-alphanumeric.
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

function stripStopwords(s: string): string {
  return s
    .split(" ")
    .filter((w) => w.length > 0 && !STOPWORDS.has(w))
    .join(" ")
}

/**
 * Strip a domain to its core word (drop TLD + non-alphanumerics) so we can
 * compare against a client name with spaces stripped. "wittebouw.nl" →
 * "wittebouw"; "rocket-leads.com" → "rocketleads".
 */
function compactDomain(domain: string): string {
  const lower = domain.toLowerCase().trim()
  // Drop the last DNS label (TLD or country code). Cheap and robust enough
  // for our use — covers .nl/.be/.com/.io/.co.uk/etc. without maintaining a
  // TLD allow-list.
  const lastDot = lower.lastIndexOf(".")
  const sansTld = lastDot > 0 ? lower.slice(0, lastDot) : lower
  return sansTld.replace(/[^a-z0-9]/g, "")
}

/**
 * Compact a client name for domain comparison: strip diacritics, lowercase,
 * and drop everything but [a-z0-9]. "Witte Bouw" → "wittebouw"; "Suits at
 * Sea" → "suitsatsea".
 */
function compactName(s: string): string {
  return normalize(s).replace(/\s+/g, "")
}

/**
 * Try every match strategy in priority order and return the first hit, or
 * null if no strategy matched. Pure function — no DB. Caller passes pre-loaded
 * clients so batch matching only hits Supabase once.
 */
export function findClientForMeeting(
  clients: ClientForMatch[],
  meeting: MeetingForMatch,
): MatchResult | null {
  // ─── Build a corpus from title + external attendee names ────────────────
  // Sales-call auto-titles ("Jouw afspraak met Sebastiaan") often don't
  // contain the company. The external attendee's name does — so feeding both
  // into the same haystack lets title-strategies catch those cases too.
  const externalAttendees = (meeting.attendees ?? []).filter((a) => a.is_external)
  const corpusParts: string[] = []
  if (meeting.title) corpusParts.push(meeting.title)
  for (const a of externalAttendees) {
    if (a.name) corpusParts.push(a.name)
  }
  const normCorpus = normalize(corpusParts.join(" "))
  const corpusStripped = stripStopwords(normCorpus)

  // ─── Strategy A: full client name appears as substring in corpus ────────
  // High-confidence: client.name "Suits at Sea" appears verbatim in
  // "suits at sea en sebastiaan". Pick the longest matching name to break
  // ties.
  if (normCorpus) {
    let bestExact: MatchResult | null = null
    let bestExactLen = 0
    for (const c of clients) {
      const normName = normalize(c.name)
      if (normName.length < MIN_CLIENT_NAME_LENGTH) continue
      if (normCorpus.includes(normName) && normName.length > bestExactLen) {
        bestExact = {
          clientId: c.mondayItemId,
          confidence: 0.9,
          strategy: "title_exact",
        }
        bestExactLen = normName.length
      }
    }
    if (bestExact) return bestExact
  }

  // ─── Strategy B: client compacted-name matches an attendee email domain ─
  // Catches the generic-title case: "Jouw afspraak met Sebastiaan" with an
  // external attendee on @wittebouw.nl. Compare both sides stripped of
  // spaces / special chars / TLDs. Bidirectional contains: matches "Witte
  // Bouw" → "wittebouw" AND "Acme" → "acmegroup". Length floor of 4 to
  // avoid 3-letter coincidences.
  for (const a of externalAttendees) {
    if (!a.email_domain) continue
    const dom = compactDomain(a.email_domain)
    if (dom.length < MIN_CLIENT_NAME_LENGTH) continue
    for (const c of clients) {
      const compactClientName = compactName(c.name)
      if (compactClientName.length < MIN_CLIENT_NAME_LENGTH) continue
      if (compactClientName === dom || compactClientName.includes(dom) || dom.includes(compactClientName)) {
        return {
          clientId: c.mondayItemId,
          confidence: 0.9,
          strategy: "attendee_domain",
        }
      }
    }
  }

  // ─── Strategy C: every word of client name appears as standalone token ─
  // Catches "Suits@Sea" → client "Suits at Sea": special chars break the
  // verbatim substring but the words still appear. Lower confidence; gets
  // `link_status='suggested'` so user confirms. Skip single-word client
  // names — they'd false-positive on too many titles.
  if (corpusStripped.length === 0) return null
  const corpusWords = new Set(corpusStripped.split(" "))
  let bestWord: MatchResult | null = null
  let bestWordLen = 0
  for (const c of clients) {
    const nameWords = stripStopwords(normalize(c.name)).split(" ").filter(Boolean)
    if (nameWords.length < 2) continue
    if (nameWords.every((w) => w.length >= 3 && corpusWords.has(w))) {
      const totalLen = nameWords.join("").length
      if (totalLen > bestWordLen) {
        bestWord = {
          clientId: c.mondayItemId,
          confidence: 0.65,
          strategy: "title_word",
        }
        bestWordLen = totalLen
      }
    }
  }
  return bestWord
}

/**
 * Apply a match result to a meeting row. Confidence threshold decides
 * whether we directly link or stage as "suggested".
 */
export async function applyMatch(
  supabase: SupabaseClient,
  meetingId: string,
  match: MatchResult,
): Promise<void> {
  const linkStatus = match.confidence >= 0.8 ? "linked" : "suggested"
  const { error } = await supabase
    .from("meetings")
    .update({ client_id: match.clientId, link_status: linkStatus })
    .eq("id", meetingId)
  if (error) throw new Error(`Failed to apply match: ${error.message}`)
}

/**
 * Match a single meeting (used post-ingest for newly inserted rows). Loads
 * clients on each call — cheap because Roy has ~100 of them. For batch
 * backfill use `runMatcherBatch` below.
 */
export async function matchSingleMeeting(
  supabase: SupabaseClient,
  meetingId: string,
): Promise<MatchResult | null> {
  const { data: meeting } = await supabase
    .from("meetings")
    .select("id, title, link_status, attendees")
    .eq("id", meetingId)
    .maybeSingle()
  if (!meeting || meeting.link_status !== "unlinked") return null

  const { data: clients } = await supabase.from("clients").select("monday_item_id, name")
  const list = (clients ?? []).map((c) => ({ mondayItemId: c.monday_item_id, name: c.name }))
  const match = findClientForMeeting(list, meeting as MeetingForMatch)
  if (!match) return null

  await applyMatch(supabase, meeting.id, match)
  return match
}

/**
 * Run the matcher across every meeting still flagged 'unlinked' OR 'archived'.
 *
 * Archived rows are intentionally re-scanned: the typical flow is
 *   sales-call comes in → archived (not yet a client) → deal closes,
 *   prospect lands in Monday → user re-runs matcher → archived row
 *   auto-links to the freshly-onboarded client.
 *
 * Idempotent: rows that don't match stay in their current state.
 */
export async function runMatcherBatch(supabase: SupabaseClient): Promise<{
  scanned: number
  linked: number
  suggested: number
  unarchivedAndLinked: number
  unmatched: number
  results: Array<{
    meetingId: string
    title: string | null
    previousStatus: string
    outcome: string
    clientId?: string
    strategy?: string
  }>
}> {
  const { data: meetings } = await supabase
    .from("meetings")
    .select("id, title, link_status, attendees")
    .in("link_status", ["unlinked", "archived"])

  const { data: clients } = await supabase.from("clients").select("monday_item_id, name")
  const clientList = (clients ?? []).map((c) => ({ mondayItemId: c.monday_item_id, name: c.name }))

  const out: Awaited<ReturnType<typeof runMatcherBatch>>["results"] = []
  let linked = 0
  let suggested = 0
  let unarchivedAndLinked = 0
  let unmatched = 0
  for (const m of (meetings ?? []) as Array<{
    id: string
    title: string | null
    link_status: string
    attendees: MeetingForMatch["attendees"]
  }>) {
    const match = findClientForMeeting(clientList, m)
    if (!match) {
      unmatched++
      out.push({
        meetingId: m.id,
        title: m.title,
        previousStatus: m.link_status,
        outcome: "unmatched",
      })
      continue
    }
    await applyMatch(supabase, m.id, match)
    const wasArchived = m.link_status === "archived"
    if (match.confidence >= 0.8) {
      linked++
      if (wasArchived) unarchivedAndLinked++
    } else {
      suggested++
    }
    out.push({
      meetingId: m.id,
      title: m.title,
      previousStatus: m.link_status,
      outcome: match.confidence >= 0.8 ? "linked" : "suggested",
      clientId: match.clientId,
      strategy: match.strategy,
    })
  }

  return {
    scanned: meetings?.length ?? 0,
    linked,
    suggested,
    unarchivedAndLinked,
    unmatched,
    results: out,
  }
}
