import { notFound } from "next/navigation"
import Image from "next/image"
import { fetchClientById } from "@/lib/integrations/monday"
import { MetaOnboardGuide } from "./_components/meta-onboard-guide"

/**
 * Client-facing Meta Business Manager onboarding guide.
 *
 * The AM sends this URL during the kick-off (auto-generated by the
 * wizard's auto-setup). It's a public page - no RL login required, the
 * client just opens the link.
 *
 * Until Meta App Review approves our `business_management` permission
 * for Embedded Signup (Sprint 6), this is a static instructional page
 * with three paths:
 *
 *   1. Klant heeft nog geen Business Manager → step-by-step BM create
 *   2. Klant heeft BM maar geen ad account in BM → ad-account create
 *   3. Klant is klaar om RL als partner toe te voegen → invite flow
 *
 * Once Embedded Signup is live, the page swaps the manual steps for a
 * "Connect with Meta" button that handles all three paths in one
 * Meta-hosted flow.
 */
export default async function MetaOnboardPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params

  // Resolve the client name from Monday so the page can greet by name.
  // 404 on a bad ID - defends against the URL being shared with
  // typos / leaks; the client list isn't enumerable via the URL anyway
  // because Monday IDs aren't sequential.
  const client = await fetchClientById(id).catch(() => null)
  if (!client) notFound()

  const greeting = client.firstName || client.companyName || client.name

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Brand bar */}
      <header className="border-b border-border/40">
        <div className="max-w-3xl mx-auto px-6 py-5 flex items-center justify-between">
          <Image
            src="/logos/logo-white-purple.svg"
            alt="Rocket Leads"
            width={140}
            height={36}
            className="h-8 w-auto hidden dark:block"
            priority
          />
          <Image
            src="/logos/logo-full-black.svg"
            alt="Rocket Leads"
            width={140}
            height={36}
            className="h-8 w-auto block dark:hidden"
            priority
          />
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10 space-y-8">
        <section>
          <p className="text-xs uppercase tracking-wide text-muted-foreground mb-2">
            Voor {client.companyName || client.name}
          </p>
          <h1 className="font-heading text-3xl font-semibold tracking-tight leading-tight mb-3">
            Hoi {greeting}, laten we Meta koppelen.
          </h1>
          <p className="text-base text-muted-foreground leading-relaxed">
            Om je advertenties te draaien hebben we toegang nodig tot jouw Meta
            Business Manager. Hieronder vind je drie scenarios - kies degene
            die op jou van toepassing is.
          </p>
        </section>

        <MetaOnboardGuide />

        <section className="rounded-2xl border border-border/60 bg-card p-5 text-sm">
          <p className="font-medium mb-1">Vragen of vastgelopen?</p>
          <p className="text-muted-foreground">
            Stuur je accountmanager een berichtje - wij helpen je live verder.
          </p>
        </section>

        <footer className="pt-6 text-[11px] text-muted-foreground text-center">
          Rocket Leads · {new Date().getFullYear()}
        </footer>
      </main>
    </div>
  )
}
