import { auth } from "@/lib/auth"
import { NextResponse, type NextRequest } from "next/server"
import Anthropic from "@anthropic-ai/sdk"
import { aiLanguageDirective } from "@/lib/ai/guardrails"
import { getAiLocale } from "@/lib/i18n/server"

/**
 * AI prefill for the Watch List "Create task" pop-up. Roy clicks the
 * Taak chip on a row → dialog opens → this endpoint fills the title and
 * body inputs with a concrete, edit-ready draft Pedro would suggest.
 *
 * Input is the same context the row already has client-side (insight,
 * 7d KPIs, category bucket) — no extra round-trips.
 *
 * Returns plain text fields the dialog can drop straight into <input> /
 * <textarea>. Failures fall back to a deterministic template (no spinner
 * forever).
 */

const anthropic = new Anthropic()

type Body = {
  clientName: string
  category: "action" | "watch" | "good"
  insight: string
  campaignManager: string | null
  kpi?: {
    adSpend?: number
    leads?: number
    cpl?: number
    prevCpl?: number
  }
}

type PrefillResponse = {
  title: string
  body: string
  /** When true, the body was generated by Claude. When false, the
   *  deterministic fallback was used (Claude call failed or skipped). */
  aiGenerated: boolean
}

function fallback(body: Body, locale: "nl" | "en"): PrefillResponse {
  // Deterministic template so the dialog always has something to show
  // even if the Claude key isn't set / quota is hit. Keeps the
  // headline / body fields immediately editable.
  const title =
    locale === "nl"
      ? `Watch List: ${body.clientName} — actie nodig`
      : `Watch List: ${body.clientName} — action needed`
  const cm = body.campaignManager?.trim() || "—"
  const insight = body.insight?.trim() || "—"
  const draftBody =
    locale === "nl"
      ? `Reden: ${insight}\n\nActie: bekijk de laatste 7d performance en stel een vervolgstap voor.\nToegewezen aan: ${cm}.`
      : `Reason: ${insight}\n\nAction: review last 7d performance and propose a next step.\nAssigned to: ${cm}.`
  return { title, body: draftBody, aiGenerated: false }
}

export async function POST(req: NextRequest) {
  const session = await auth()
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const body = (await req.json().catch(() => null)) as Body | null
  if (!body?.clientName) {
    return NextResponse.json({ error: "clientName required" }, { status: 400 })
  }

  const locale = await getAiLocale()

  // Compact context block — small enough to send to Haiku without the
  // full Pedro guardrails stack (this isn't a Pedro insight, it's a
  // copy-write task).
  const kpiLines: string[] = []
  if (body.kpi) {
    const k = body.kpi
    if (typeof k.adSpend === "number") kpiLines.push(`Ad spend (7d): €${k.adSpend.toFixed(0)}`)
    if (typeof k.leads === "number") kpiLines.push(`Leads (7d): ${k.leads}`)
    if (typeof k.cpl === "number" && k.cpl > 0) kpiLines.push(`CPL (7d): €${k.cpl.toFixed(2)}`)
    if (typeof k.prevCpl === "number" && k.prevCpl > 0) kpiLines.push(`CPL (prev 7d): €${k.prevCpl.toFixed(2)}`)
  }
  const kpiBlock = kpiLines.length > 0 ? kpiLines.join("\n") : "(no KPI snapshot)"

  const userPrompt = `Je schrijft een korte taak voor de Campaign Manager van een Rocket Leads klant. De taak verschijnt in de Hub-inbox van de CM met een deadline van vandaag. Doel: de CM weet binnen 5 seconden wat er aan de hand is en wat de eerstvolgende stap is.

Klant: ${body.clientName}
Watch List bucket: ${body.category}
Insight die op de Watch List staat: ${body.insight || "(geen)"}
Campaign Manager: ${body.campaignManager || "(onbekend)"}

KPI snapshot:
${kpiBlock}

Schrijf:
- TITLE: één zin, max 80 tekens, geen punt aan het eind. Geen quote-tekens. Begin met de klantnaam OF met de actie ("Pauzeer …", "Check …", "Refresh creatives voor …"). Geen "Watch List:" prefix nodig.
- BODY: 3-5 regels (gebruik newlines, geen bullets). Eerste regel = waarom (één feit met cijfer + window-label). Tweede regel = concrete eerstvolgende stap. Optioneel derde regel = vraag waarop de CM moet antwoorden of context (welke ad, welke campagne).

GEEN:
- Geen verzonnen cijfers — gebruik alleen wat in de KPI snapshot of de insight staat.
- Geen budget-increase suggesties (klanten zitten op vast budget).
- Geen "Hi {name}" / "Hey CM" — dit is een inbox-taak, geen mail.
- Geen markdown (geen **, geen #, geen lijsten).

Output STRICT JSON, niets erbuiten:
{"title": "…", "body": "…"}${aiLanguageDirective(locale)}`

  try {
    const message = await anthropic.messages.create({
      // Haiku is plenty for a 5-line copy task and 5-10x faster than
      // Sonnet — the dialog can't wait 4 seconds for a draft.
      model: "claude-haiku-4-5-20251001",
      max_tokens: 400,
      messages: [{ role: "user", content: userPrompt }],
    })
    const raw = message.content[0]?.type === "text" ? message.content[0].text : ""
    const cleaned = raw.replace(/```json|```/g, "").trim()
    const parsed = JSON.parse(cleaned) as { title?: string; body?: string }
    if (!parsed.title?.trim() || !parsed.body?.trim()) {
      return NextResponse.json(fallback(body, locale))
    }
    return NextResponse.json({
      title: parsed.title.trim().slice(0, 120),
      body: parsed.body.trim().slice(0, 800),
      aiGenerated: true,
    } satisfies PrefillResponse)
  } catch (e) {
    console.error("task-prefill: Claude call failed", e)
    return NextResponse.json(fallback(body, locale))
  }
}
