-- Pedro variants gain image-generation columns.
--
-- The text → image leap: Pedro now writes an `imagePrompt` per variant
-- describing the visual brief. The CM clicks "Genereer image", we call
-- Gemini (Nano Banana Pro / gemini-3-pro-image) with the winner's
-- thumbnail as a reference + the imagePrompt → returns a brand-
-- consistent variant image. The image lands in Supabase Storage and
-- the variant row gains a storage path we re-sign on read.
--
-- Storage bucket `pedro-ad-images` is auto-created on first use via
-- the admin client (see src/lib/integrations/pedro-image-storage.ts).
-- Private bucket, signed URLs only — never store baked URLs because
-- they expire.
--
-- Roy 2026-06-09: "Pedro moet ook de image maken — anders blijft de
-- one-click upload half."

ALTER TABLE pedro_variants
  -- The visual brief Pedro generates alongside the copy. Used as the
  -- prompt for the image-gen call; also the basis for the CM's
  -- "regenereer met edits" workflow (edit prompt → re-call).
  ADD COLUMN IF NOT EXISTS image_prompt text,
  -- Storage path within the pedro-ad-images bucket.
  --   Pattern: <client_id>/<variant_id>/<timestamp>.jpg
  -- We re-sign URLs on read; never store a baked URL.
  ADD COLUMN IF NOT EXISTS image_storage_path text,
  -- High-level provider — kept generic so we can swap models without
  -- a schema migration. Specific model goes in image_model below.
  ADD COLUMN IF NOT EXISTS image_provider text
    CHECK (image_provider IN ('gemini', 'manual_upload')),
  -- Specific model identifier — lets us A/B test 2.5 Flash Image vs
  -- 3 Pro Image (Nano Banana Pro), and lets the learning loop later
  -- distinguish "winner generated by model X" from "winner generated
  -- by model Y".
  ADD COLUMN IF NOT EXISTS image_model text,
  ADD COLUMN IF NOT EXISTS image_generated_at timestamptz,
  -- Width/height tells the launch endpoint which Meta placement to
  -- target (1:1 = Feed, 9:16 = Reels, etc.).
  ADD COLUMN IF NOT EXISTS image_width integer,
  ADD COLUMN IF NOT EXISTS image_height integer;

-- Track which variants have been launched into Meta — set by the
-- /launch endpoint (Fase C), used by the UI to gate "Open in Meta"
-- vs "Launch". This is on top of `meta_ad_id` which the sync cron
-- ALSO writes; the difference is meta_ad_launched_at fires
-- immediately at launch time, meta_ad_id might lag or be empty if
-- launch failed mid-way.
ALTER TABLE pedro_variants
  ADD COLUMN IF NOT EXISTS meta_ad_launched_at timestamptz,
  ADD COLUMN IF NOT EXISTS meta_launch_error text;

NOTIFY pgrst, 'reload schema';
